apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chirpstack-v3-to-v4.fullname" . }}-config-v3
data:
{{ (.Files.Glob "configurations/v3/as/*").AsConfig | indent 2 }}
{{ (.Files.Glob "configurations/v3/ns/*").AsConfig | indent 2 }}
