apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chirpstack-v3-to-v4.fullname" . }}
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: {{ include "chirpstack-v3-to-v4.serviceAccountName" . }}
      containers:
        - name: migration
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "chirpstack-v3-to-v4"
          args:
            {{ range $path, $_ :=  .Files.Glob  "configurations/v3/as/*" }}
            - "--as-config-file"
            - "/v3/{{ base $path }}"
            {{ end }}
            {{ range $path, $_ :=  .Files.Glob  "configurations/v4/cs/*" }}
            - "--cs-config-file"
            - "/v4/{{ base $path }}"
            {{ end }}
            {{ range $path, $_ :=  .Files.Glob  "configurations/v3/ns/*" }}
            - "--ns-config-file"
            - "/v3/{{ base $path }}"
            {{ end }}
          {{- if .Values.resources }}
          resources: {{- toYaml .Values.backup.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: config-v3
              mountPath: /v3
            - name: config-v4
              mountPath: /v4
      volumes:
        - name: config-v3
          configMap:
            name: {{ include "chirpstack-v3-to-v4.fullname" . }}-config-v3
        - name: config-v4
          configMap:
            name: {{ include "chirpstack-v3-to-v4.fullname" . }}-config-v4
      restartPolicy: Never
